/**
 * Baseline City of Tshwane ops floor. Coordinates are real suburbs; account
 * numbers and households are representative, not live CIS records.
 */

import { appendAudit } from "./engines/audit";
import { computePriorityScore } from "./engines/priority";
import { evidenceSvg } from "./evidence";
import { daysAgo, hoursAgo, minutesAgo, nowIso } from "./id";
import type {
  AuditLog,
  Feeder,
  FieldCrew,
  LiveEvent,
  MasterIncident,
  Meter,
  OutageReport,
  PlatformSnapshot,
  RevenueInvestigation,
  User,
  VendingTelemetryLog,
} from "./types";

const T0 = new Date();

function pt(lon: number, lat: number) {
  return { lon, lat };
}

export function seedPlatform(): PlatformSnapshot {
  const users: User[] = [
    {
      id: "usr_system",
      employeeNo: "SYS-000",
      fullName: "ElectroRaid Engine",
      email: "engine@electroraid.tshwane.gov.za",
      phone: null,
      role: "system",
      isActive: true,
      createdAt: daysAgo(400, T0),
    },
    {
      id: "usr_sibusiso",
      employeeNo: null,
      fullName: "Sibusiso Mabena",
      email: "sibusiso@resident.tshwane",
      phone: "+27 82 441 0190",
      role: "resident",
      isActive: true,
      createdAt: daysAgo(40, T0),
    },
    {
      id: "usr_thandiwe",
      employeeNo: "COT-4412",
      fullName: "Thandiwe Nkosi",
      email: "t.nkosi@tshwane.gov.za",
      phone: "+27 12 358 4412",
      role: "dispatcher",
      isActive: true,
      createdAt: daysAgo(210, T0),
    },
    {
      id: "usr_sipho",
      employeeNo: "COT-2281",
      fullName: "Sipho Dlamini",
      email: "s.dlamini@tshwane.gov.za",
      phone: "+27 82 441 2281",
      role: "technician",
      isActive: true,
      createdAt: daysAgo(180, T0),
    },
    {
      id: "usr_lebo",
      employeeNo: "COT-2288",
      fullName: "Lebogang Maseko",
      email: "l.maseko@tshwane.gov.za",
      phone: "+27 83 118 9902",
      role: "technician",
      isActive: true,
      createdAt: daysAgo(140, T0),
    },
    {
      id: "usr_nomsa",
      employeeNo: "RP-1104",
      fullName: "Nomsa Khumalo",
      email: "n.khumalo@tshwane.gov.za",
      phone: "+27 72 334 1104",
      role: "revenue_inspector",
      isActive: true,
      createdAt: daysAgo(95, T0),
    },
    {
      id: "usr_pieter",
      employeeNo: "RP-1109",
      fullName: "Pieter van Wyk",
      email: "p.vanwyk@tshwane.gov.za",
      phone: "+27 71 220 4488",
      role: "revenue_inspector",
      isActive: true,
      createdAt: daysAgo(70, T0),
    },
    {
      id: "usr_cfo",
      employeeNo: "EX-009",
      fullName: "Office of the CFO",
      email: "cfo.energy@tshwane.gov.za",
      phone: "+27 12 358 9999",
      role: "executive",
      isActive: true,
      createdAt: daysAgo(500, T0),
    },
  ];

  const crews: FieldCrew[] = [
    {
      id: "crew_mt_mamelodi",
      userId: "usr_sipho",
      callsign: "MT-12 Mamelodi",
      specialization: "maintenance",
      skillCertifications: ["MV_JOINTING", "OHL_REPAIR", "MINI_SUB"],
      status: "en_route",
      location: pt(28.3721, -25.7318),
      vehicleReg: "CT 441 GP",
      activeQueueSize: 1,
      lastGpsAt: minutesAgo(2, T0),
    },
    {
      id: "crew_mt_west",
      userId: "usr_lebo",
      callsign: "MT-07 Atteridgeville",
      specialization: "maintenance",
      skillCertifications: ["CABLE_FAULT", "LV_BOARD", "STREETLIGHT"],
      status: "en_route",
      location: pt(28.0922, -25.7704),
      vehicleReg: "CT 228 GP",
      activeQueueSize: 1,
      lastGpsAt: minutesAgo(1, T0),
    },
    {
      id: "crew_rp_east",
      userId: "usr_nomsa",
      callsign: "RP-03 East",
      specialization: "revenue_protection",
      skillCertifications: ["METER_TAMPER", "PREPAID_AUDIT", "IZINYOKA"],
      status: "available",
      location: pt(28.241, -25.741),
      vehicleReg: "CT 904 GP",
      activeQueueSize: 0,
      lastGpsAt: minutesAgo(3, T0),
    },
    {
      id: "crew_rp_west",
      userId: "usr_pieter",
      callsign: "RP-01 West",
      specialization: "revenue_protection",
      skillCertifications: ["METER_TAMPER", "BACKBILL", "PHOTO_EVIDENCE"],
      status: "available",
      location: pt(28.118, -25.782),
      vehicleReg: "CT 117 GP",
      activeQueueSize: 1,
      lastGpsAt: minutesAgo(4, T0),
    },
  ];

  const feeders: Feeder[] = [
    {
      id: "fdr_mam_12",
      code: "MAM-F12",
      name: "Mamelodi Ext 11 / Tsamaya 11 kV",
      suburb: "Mamelodi",
      status: "ENERGIZED",
      location: pt(28.3932, -25.7228),
      updatedAt: minutesAgo(8, T0),
    },
    {
      id: "fdr_att_04",
      code: "ATT-F04",
      name: "Atteridgeville Maunde 11 kV",
      suburb: "Atteridgeville",
      status: "FAULT",
      location: pt(28.0704, -25.7758),
      updatedAt: minutesAgo(22, T0),
    },
    {
      id: "fdr_sos_09",
      code: "SOS-F09",
      name: "Soshanguve Block L Mini-sub",
      suburb: "Soshanguve",
      status: "ENERGIZED",
      location: pt(28.1022, -25.5284),
      updatedAt: minutesAgo(11, T0),
    },
    {
      id: "fdr_hat_02",
      code: "HAT-F02",
      name: "Hatfield / Steve Biko 11 kV",
      suburb: "Hatfield",
      status: "DEENERGIZED",
      location: pt(28.2376, -25.7472),
      updatedAt: hoursAgo(5, T0),
    },
    {
      id: "fdr_cbd_01",
      code: "CBD-F01",
      name: "Pretoria CBD Church Square",
      suburb: "Pretoria CBD",
      status: "ENERGIZED",
      location: pt(28.1879, -25.7463),
      updatedAt: minutesAgo(6, T0),
    },
  ];

  const meters: Meter[] = [
    {
      id: "mtr_silent_mam",
      accountNumber: "3218841907",
      meterNumber: "PRE-778221",
      householdName: "M. Radebe",
      address: "884 Section D, Tsamaya Road, Mamelodi East",
      suburb: "Mamelodi",
      location: pt(28.4012, -25.7186),
      feederId: "fdr_mam_12",
      status: "active",
      tariffCentsKwh: 285,
      installedAt: daysAgo(640, T0),
      lastPurchaseAt: daysAgo(87, T0),
    },
    {
      id: "mtr_healthy_mam",
      accountNumber: "3218840441",
      meterNumber: "PRE-441902",
      householdName: "S. Mabena",
      address: "12 Tsamaya Road, Mamelodi Ext 11",
      suburb: "Mamelodi",
      location: pt(28.394, -25.7234),
      feederId: "fdr_mam_12",
      status: "active",
      tariffCentsKwh: 285,
      installedAt: daysAgo(400, T0),
      lastPurchaseAt: daysAgo(3, T0),
    },
    {
      id: "mtr_dark_hat",
      accountNumber: "3081120091",
      meterNumber: "PRE-190221",
      householdName: "A. Naidoo",
      address: "44 Burnett Street, Hatfield",
      suburb: "Hatfield",
      location: pt(28.2391, -25.7488),
      feederId: "fdr_hat_02",
      status: "active",
      tariffCentsKwh: 312,
      installedAt: daysAgo(900, T0),
      lastPurchaseAt: daysAgo(71, T0),
    },
    {
      id: "mtr_att_closed",
      accountNumber: "3172208811",
      meterNumber: "PRE-662190",
      householdName: "K. Mokoena",
      address: "109 Maunde Street, Atteridgeville",
      suburb: "Atteridgeville",
      location: pt(28.0688, -25.7771),
      feederId: "fdr_att_04",
      status: "confirmed_tamper",
      tariffCentsKwh: 285,
      installedAt: daysAgo(520, T0),
      lastPurchaseAt: daysAgo(94, T0),
    },
    {
      id: "mtr_sos_ok",
      accountNumber: "3290014472",
      meterNumber: "PRE-330118",
      householdName: "F. Baloyi",
      address: "Block L 441, Soshanguve",
      suburb: "Soshanguve",
      location: pt(28.1044, -25.5298),
      feederId: "fdr_sos_09",
      status: "active",
      tariffCentsKwh: 265,
      installedAt: daysAgo(300, T0),
      lastPurchaseAt: daysAgo(1, T0),
    },
  ];

  const vending: VendingTelemetryLog[] = [
    vend("mtr_silent_mam", daysAgo(87, T0), 20, 57),
    vend("mtr_healthy_mam", daysAgo(18, T0), 50, 142.5),
    vend("mtr_healthy_mam", daysAgo(3, T0), 40, 114),
    vend("mtr_dark_hat", daysAgo(71, T0), 30, 93.6),
    vend("mtr_att_closed", daysAgo(94, T0), 10, 28.5),
    vend("mtr_sos_ok", daysAgo(1, T0), 60, 159),
  ];

  const attOpened = hoursAgo(1.4, T0);
  const sosOpened = hoursAgo(0.55, T0);
  const northOpened = hoursAgo(3.2, T0);
  const hatResolvedOpen = hoursAgo(9, T0);
  const hatResolvedClose = hoursAgo(6.4, T0);
  const mamOpened = hoursAgo(2.4, T0);
  const mamOnSite = minutesAgo(22, T0);
  const mamResolved = minutesAgo(8, T0);

  const incidents: MasterIncident[] = [
    {
      id: "inc_att_cable",
      reference: "TSH-OUT-2026-0188",
      classification: "cable_fault",
      status: "en_route",
      location: pt(28.0704, -25.7758),
      address: "Maunde Street near Kalafong Hospital, Atteridgeville",
      suburb: "Atteridgeville",
      feederId: "fdr_att_04",
      affectedHouseholds: 86,
      criticalInfrastructure: true,
      priorityScore: computePriorityScore(86, true, attOpened, T0),
      assignedCrewId: "crew_mt_west",
      dispatchedAt: hoursAgo(1.15, T0),
      onSiteAt: null,
      resolvedAt: null,
      firstReportedAt: attOpened,
      lastActivityAt: hoursAgo(0.4, T0),
    },
    {
      id: "inc_sos_tx",
      reference: "TSH-OUT-2026-0191",
      classification: "transformer_fault",
      status: "open",
      location: pt(28.1022, -25.5284),
      address: "Mini-sub Block L, Soshanguve",
      suburb: "Soshanguve",
      feederId: "fdr_sos_09",
      affectedHouseholds: 41,
      criticalInfrastructure: false,
      priorityScore: computePriorityScore(41, false, sosOpened, T0),
      assignedCrewId: null,
      dispatchedAt: null,
      onSiteAt: null,
      resolvedAt: null,
      firstReportedAt: sosOpened,
      lastActivityAt: minutesAgo(12, T0),
    },
    {
      id: "inc_north_lights",
      reference: "TSH-OUT-2026-0184",
      classification: "streetlight",
      status: "open",
      location: pt(28.1762, -25.6794),
      address: "President Steyn Street, Pretoria North",
      suburb: "Pretoria North",
      feederId: "fdr_cbd_01",
      affectedHouseholds: 4,
      criticalInfrastructure: false,
      priorityScore: computePriorityScore(4, false, northOpened, T0),
      assignedCrewId: null,
      dispatchedAt: null,
      onSiteAt: null,
      resolvedAt: null,
      firstReportedAt: northOpened,
      lastActivityAt: hoursAgo(2.1, T0),
    },
    {
      id: "inc_hat_done",
      reference: "TSH-OUT-2026-0179",
      classification: "voltage_fluctuation",
      status: "resolved",
      location: pt(28.2376, -25.7472),
      address: "Festival Street, Hatfield",
      suburb: "Hatfield",
      feederId: "fdr_hat_02",
      affectedHouseholds: 12,
      criticalInfrastructure: false,
      priorityScore: computePriorityScore(12, false, hatResolvedOpen, T0),
      assignedCrewId: "crew_mt_mamelodi",
      dispatchedAt: hoursAgo(8.4, T0),
      onSiteAt: hoursAgo(7.9, T0),
      resolvedAt: hatResolvedClose,
      firstReportedAt: hatResolvedOpen,
      lastActivityAt: hatResolvedClose,
    },
    {
      id: "inc_mam_done",
      reference: "TSH-OUT-2026-0193",
      classification: "no_power",
      status: "resolved",
      location: pt(28.394, -25.7234),
      address: "12 Tsamaya Road, Mamelodi Ext 11",
      suburb: "Mamelodi",
      feederId: "fdr_mam_12",
      affectedHouseholds: 18,
      criticalInfrastructure: false,
      priorityScore: computePriorityScore(18, false, mamOpened, T0),
      assignedCrewId: "crew_mt_mamelodi",
      dispatchedAt: hoursAgo(2.1, T0),
      onSiteAt: mamOnSite,
      resolvedAt: mamResolved,
      firstReportedAt: mamOpened,
      lastActivityAt: mamResolved,
    },
    {
      id: "inc_mam_live",
      reference: "TSH-OUT-2026-0194",
      classification: "cable_fault",
      status: "en_route",
      location: pt(28.3952, -25.7241),
      address: "9 Tsamaya Road, Mamelodi Ext 11",
      suburb: "Mamelodi",
      feederId: "fdr_mam_12",
      affectedHouseholds: 22,
      criticalInfrastructure: false,
      priorityScore: computePriorityScore(22, false, minutesAgo(18, T0), T0),
      assignedCrewId: "crew_mt_mamelodi",
      dispatchedAt: minutesAgo(8, T0),
      onSiteAt: null,
      resolvedAt: null,
      firstReportedAt: minutesAgo(18, T0),
      lastActivityAt: minutesAgo(8, T0),
    },
  ];

  const reports: OutageReport[] = [
    rpt("inc_att_cable", "3172201100", "Lindiwe Sithole", pt(28.0701, -25.7754), "88 Maunde Street, Atteridgeville", "cable_fault", "call_centre", attOpened, "Hospital corridor dark."),
    rpt("inc_att_cable", "3172201108", "J. Kekana", pt(28.0712, -25.7766), "Kalafong staff village", "no_power", "app", hoursAgo(1.25, T0), null),
    rpt("inc_att_cable", null, "Anonymous", pt(28.0694, -25.7749), "Maunde / Phomolong", "no_power", "whatsapp", hoursAgo(1.1, T0), null),
    rpt("inc_sos_tx", "3290014401", "T. Mashaba", pt(28.1018, -25.5281), "Block L 12, Soshanguve", "transformer_fault", "sms", sosOpened, "Mini-sub smoking."),
    rpt("inc_sos_tx", "3290014419", "P. Nkosi", pt(28.1033, -25.529), "Block L 40, Soshanguve", "no_power", "app", minutesAgo(28, T0), null),
    rpt("inc_north_lights", "3058810021", "Ward 5 office", pt(28.1762, -25.6794), "President Steyn Street", "streetlight", "walk_in", northOpened, null),
    rpt("inc_hat_done", "3081120004", "Campus protection", pt(28.2376, -25.7472), "Festival Street, Hatfield", "voltage_fluctuation", "call_centre", hatResolvedOpen, null),
    rpt("inc_mam_done", "3218840441", "Sibusiso Mabena", pt(28.394, -25.7234), "12 Tsamaya Road, Mamelodi Ext 11", "no_power", "whatsapp", mamOpened, "Whole street dark after a bang."),
    rpt(
      "inc_mam_live",
      "3218840441",
      "Sibusiso Mabena",
      pt(28.3952, -25.7241),
      "9 Tsamaya Road, Mamelodi Ext 11",
      "cable_fault",
      "app",
      minutesAgo(18, T0),
      "No power on this side of Tsamaya after the cable popped.",
    ),
  ];

  const investigations: RevenueInvestigation[] = [
    {
      id: "inv_att_closed",
      reference: "TSH-RP-2026-0044",
      type: "meter_tamper",
      status: "closed_recovered",
      meterId: "mtr_att_closed",
      feederId: "fdr_att_04",
      location: pt(28.0688, -25.7771),
      address: "109 Maunde Street, Atteridgeville",
      suburb: "Atteridgeville",
      anomalyRiskScore: 91,
      daysZeroConsumption: 94,
      assignedCrewId: "crew_rp_west",
      dispatchedAt: daysAgo(2.2, T0),
      onSiteAt: daysAgo(2.1, T0),
      fineAmountZar: 15000,
      backbillZar: 24890,
      penaltyZar: 3500,
      evidence: [
        {
          id: "evd_att_1",
          caption: "Bypass jumper on incoming tails",
          dataUri: evidenceSvg("Bypass jumper", "Incoming tails bridged ahead of the prepaid meter."),
          capturedAt: daysAgo(2.1, T0),
          capturedBy: "usr_pieter",
        },
      ],
      notes: "Confirmed illegal jumper. Meter resealed. Back-bill 94 days @ 9.4 kWh/day.",
      createdAt: daysAgo(3, T0),
      closedAt: daysAgo(1.8, T0),
    },
    {
      id: "inv_sos_tip",
      reference: "TSH-RP-2026-0048",
      type: "izinyoka_tip",
      status: "flagged",
      meterId: null,
      feederId: "fdr_sos_09",
      location: pt(28.1088, -25.5315),
      address: "Informal tap off Mabopane highway feeder, Soshanguve",
      suburb: "Soshanguve",
      anomalyRiskScore: 74,
      daysZeroConsumption: null,
      assignedCrewId: null,
      dispatchedAt: null,
      onSiteAt: null,
      fineAmountZar: 0,
      backbillZar: 0,
      penaltyZar: 0,
      evidence: [],
      notes: "Anonymous WhatsApp tip: overhead tap feeding three shacks behind Block L spaza.",
      createdAt: hoursAgo(4, T0),
      closedAt: null,
    },
  ];

  let audit: AuditLog[] = [];
  const writes: Parameters<typeof appendAudit>[1][] = [
    {
      actorId: "usr_system",
      actorRole: "system",
      actionType: "PLATFORM_SEEDED",
      entityType: "platform",
      entityId: "electroraid",
      payload: { city: "Tshwane", mode: "prototype" },
      occurredAt: daysAgo(3, T0),
    },
    {
      actorId: "usr_system",
      actorRole: "system",
      actionType: "ANOMALY_ZERO_CONSUMPTION_FLAGGED",
      entityType: "revenue_investigation",
      entityId: "inv_att_closed",
      location: pt(28.0688, -25.7771),
      payload: { reference: "TSH-RP-2026-0044", daysZero: 94, riskScore: 91 },
      occurredAt: daysAgo(3, T0),
    },
    {
      actorId: "usr_thandiwe",
      actorRole: "dispatcher",
      actionType: "DISPATCHER_ASSIGNED_CREW",
      entityType: "revenue_investigation",
      entityId: "inv_att_closed",
      payload: { callsign: "RP-01 West", technicianName: "Pieter van Wyk" },
      occurredAt: daysAgo(2.2, T0),
    },
    {
      actorId: "usr_pieter",
      actorRole: "revenue_inspector",
      actionType: "FIELD_UNIT_ON_SITE",
      entityType: "revenue_investigation",
      entityId: "inv_att_closed",
      location: pt(28.0688, -25.7771),
      payload: { status: "on_site" },
      occurredAt: daysAgo(2.1, T0),
    },
    {
      actorId: "usr_pieter",
      actorRole: "revenue_inspector",
      actionType: "INSPECTOR_EVIDENCE_UPLOADED",
      entityType: "revenue_investigation",
      entityId: "inv_att_closed",
      payload: { caption: "Bypass jumper on incoming tails" },
      occurredAt: daysAgo(2.1, T0),
    },
    {
      actorId: "usr_pieter",
      actorRole: "revenue_inspector",
      actionType: "TAMPER_FINE_ISSUED",
      entityType: "revenue_investigation",
      entityId: "inv_att_closed",
      payload: { fineAmountZar: 15000, backbillZar: 24890, penaltyZar: 3500, totalZar: 43390 },
      occurredAt: daysAgo(2, T0),
    },
    {
      actorId: "usr_pieter",
      actorRole: "revenue_inspector",
      actionType: "INVESTIGATION_CLOSED",
      entityType: "revenue_investigation",
      entityId: "inv_att_closed",
      payload: { status: "closed_recovered", reference: "TSH-RP-2026-0044" },
      occurredAt: daysAgo(1.8, T0),
    },
    {
      actorId: "usr_system",
      actorRole: "resident",
      actionType: "ANONYMOUS_IZINYOKA_TIP",
      entityType: "revenue_investigation",
      entityId: "inv_sos_tip",
      location: pt(28.1088, -25.5315),
      payload: { channel: "whatsapp", suburb: "Soshanguve" },
      occurredAt: hoursAgo(4, T0),
    },
    {
      actorId: "usr_thandiwe",
      actorRole: "dispatcher",
      actionType: "DISPATCHER_ASSIGNED_CREW",
      entityType: "master_incident",
      entityId: "inc_att_cable",
      payload: { callsign: "MT-07 Atteridgeville", technicianName: "Lebogang Maseko", critical: true },
      occurredAt: hoursAgo(1.15, T0),
    },
    {
      actorId: "usr_sipho",
      actorRole: "technician",
      actionType: "TECHNICIAN_WORK_COMPLETED",
      entityType: "master_incident",
      entityId: "inc_hat_done",
      payload: { reference: "TSH-OUT-2026-0179", notes: "Tap-changer reset, voltage restored." },
      occurredAt: hatResolvedClose,
    },
    {
      actorId: "usr_thandiwe",
      actorRole: "dispatcher",
      actionType: "DISPATCHER_ASSIGNED_CREW",
      entityType: "master_incident",
      entityId: "inc_mam_done",
      payload: { callsign: "MT-12 Mamelodi", technicianName: "Sipho Dlamini" },
      occurredAt: hoursAgo(2.1, T0),
    },
    {
      actorId: "usr_sipho",
      actorRole: "technician",
      actionType: "FIELD_UNIT_ON_SITE",
      entityType: "master_incident",
      entityId: "inc_mam_done",
      location: pt(28.394, -25.7234),
      payload: { status: "on_site" },
      occurredAt: mamOnSite,
    },
    {
      actorId: "usr_sipho",
      actorRole: "technician",
      actionType: "TECHNICIAN_WORK_COMPLETED",
      entityType: "master_incident",
      entityId: "inc_mam_done",
      payload: {
        reference: "TSH-OUT-2026-0193",
        notes: "Replaced failed 11 kV cable joint. Supply restored.",
      },
      occurredAt: mamResolved,
    },
  ];
  for (const w of writes) audit = [...audit, appendAudit(audit, w)];

  const events: LiveEvent[] = [
    {
      id: "evt_seed_1",
      type: "incident.opened",
      title: "Cable fault · Atteridgeville",
      detail: "86 households · Kalafong flagged as critical infrastructure",
      at: attOpened,
      severity: "critical",
      entityType: "master_incident",
      entityId: "inc_att_cable",
    },
    {
      id: "evt_seed_2",
      type: "dispatch.assigned",
      title: "MT-07 dispatched to Maunde Street",
      detail: "Lebogang Maseko · 11 min ETA at assignment",
      at: hoursAgo(1.15, T0),
      severity: "info",
      entityType: "master_incident",
      entityId: "inc_att_cable",
    },
    {
      id: "evt_seed_3",
      type: "incident.opened",
      title: "Mini-sub fault · Soshanguve Block L",
      detail: "41 households on SOS-F09",
      at: sosOpened,
      severity: "warn",
      entityType: "master_incident",
      entityId: "inc_sos_tx",
    },
    {
      id: "evt_seed_mam_live_dispatch",
      type: "dispatch.assigned",
      title: "MT-12 dispatched to Tsamaya Road",
      detail: "Sipho Dlamini · 8 min ETA · job assigned · resident can track live",
      at: minutesAgo(8, T0),
      severity: "info",
      entityType: "master_incident",
      entityId: "inc_mam_live",
    },
    {
      id: "evt_seed_mam_onsite",
      type: "field.onsite",
      title: "Technician logged on site · Mamelodi",
      detail:
        "12 Tsamaya Road, Mamelodi Ext 11. Please watch for the crew and confirm when power returns.",
      at: mamOnSite,
      severity: "info",
      entityType: "master_incident",
      entityId: "inc_mam_done",
    },
    {
      id: "evt_seed_mam_done",
      type: "incident.resolved",
      title: "TSH-OUT-2026-0193 — technician finished",
      detail:
        "Mamelodi: crew says supply is restored. Please confirm if your lights are back.",
      at: mamResolved,
      severity: "success",
      entityType: "master_incident",
      entityId: "inc_mam_done",
    },
    {
      id: "evt_seed_mam_wait",
      type: "incident.opened",
      title: "Waiting for a technician · Mamelodi Ext 11",
      detail:
        "Sibusiso reported TSH-OUT-2026-0194. Dispatcher must assign a van — then the household tracks it live.",
      at: minutesAgo(18, T0),
      severity: "warn",
      entityType: "master_incident",
      entityId: "inc_mam_live",
    },
  ];

  return {
    users,
    crews,
    feeders,
    meters,
    vending,
    incidents,
    reports,
    investigations,
    audit,
    events,
    weights: {
      wHouseholds: 12,
      wCritical: 280,
      wElapsed: 1.8,
    },
  };
}

function vend(
  meterId: string,
  purchasedAt: string,
  kwh: number,
  amountZar: number,
): VendingTelemetryLog {
  return {
    id: `vnd_${meterId}_${purchasedAt.slice(0, 10)}`,
    meterId,
    purchasedAt,
    kwh,
    amountZar,
    vendorId: "COT-VEND-441",
    tokenMasked: "**** **** **** 7712",
  };
}

function rpt(
  masterIncidentId: string,
  accountNumber: string | null,
  reporterName: string,
  location: { lon: number; lat: number },
  address: string,
  classification: OutageReport["classification"],
  channel: OutageReport["channel"],
  reportedAt: string,
  notes: string | null,
): OutageReport {
  return {
    id: `rpt_${masterIncidentId}_${reporterName.replace(/\W/g, "").slice(0, 8).toLowerCase()}`,
    masterIncidentId,
    accountNumber,
    reporterName,
    contactPhone: accountNumber ? "+27 72 000 0000" : null,
    location,
    address,
    classification,
    channel,
    notes,
    reportedAt,
  };
}

export { nowIso };
